export const GET_ABOUTINFO = "GET_ABOUTINFO";
export const GET_DOCTORINFO = "GET_DOCTORINFO";
export const GET_OURSERVICES = "GET_OURSERVICES";
export const GET_CLINICINFO = "GET_CLINICINFO";
export const GET_SLIDERIMAGES = "GET_SLIDERIMAGES";
export const POST_APPOINTMENT = "POST_APPOINTMENT";
